server:
  port: 8080

spring:
  application:
    name: Config-client
  cloud:
    config:
      uri: http://localhost:8888

config:
  items:
    - Java
    - spring
    - Quarkus
    - Micronaut
    - J2EE
    - Android